-- Publish marker used by the Admin Panel and the notification webhook.
alter table public.apps add column if not exists update_available boolean not null default false;

-- Device tokens used by the PaliaAPK HUB publish-notification service.
create table if not exists public.device_push_tokens (
  id bigint generated by default as identity primary key,
  token text not null unique,
  platform text not null default 'android' check (platform in ('android')),
  app_id text not null default 'com.shanpalia.paliaapkhub',
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

alter table public.device_push_tokens enable row level security;

-- The app may register its own FCM token. Tokens cannot be read by anonymous clients.
drop policy if exists "Allow anonymous device token registration" on public.device_push_tokens;
create policy "Allow anonymous device token registration"
  on public.device_push_tokens for insert to anon
  with check (platform = 'android' and app_id = 'com.shanpalia.paliaapkhub');

-- No SELECT policy is intentionally provided. The notification sender must use a
-- server-side service-role credential, never the anon key, to read recipients.
