const SUPABASE_URL="https://ralinnuegsbuvlhwpzln.supabase.co",SUPABASE_KEY="sb_publishable_pXsTbFOseqm5uuA0hzqSzQ_UJxdvQi9";const db=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const firebaseConfig={apiKey:"AIzaSyCn7GUkOaFO4l0x1zM5mwW4hFkW2ISxR10",authDomain:"shanpalia-apk-hub.firebaseapp.com",projectId:"shanpalia-apk-hub",storageBucket:"shanpalia-apk-hub.firebasestorage.app",messagingSenderId:"270953807883",appId:"1:270953807883:web:c900f4409938f16477870e"};if(!firebase.apps.length)firebase.initializeApp(firebaseConfig);const auth=firebase.auth();const $=id=>document.getElementById(id);let apps=[];
$("authBtn").onclick=()=>$("authModal").classList.remove("hidden");$("bottomAuth").onclick=()=>$("authModal").classList.remove("hidden");$("closeAuth").onclick=()=>$("authModal").classList.add("hidden");
$("login").onclick=async()=>{try{clearErr();await auth.signInWithEmailAndPassword($("email").value.trim(),$("password").value)}catch(e){showErr(e.message)}};$("signup").onclick=async()=>{try{clearErr();await auth.createUserWithEmailAndPassword($("email").value.trim(),$("password").value)}catch(e){showErr(e.message)}};$("logout").onclick=()=>auth.signOut();
auth.onAuthStateChanged(u=>{if(u){$("authBtn").textContent=(u.email||"Account").split("@")[0];$("logout").classList.remove("hidden")}else{$("authBtn").textContent="Sign in";$("logout").classList.add("hidden")}});
function showErr(x){$("authError").textContent=x}function clearErr(){$("authError").textContent=""}
async function loadApps(){ $("status").textContent="Loading apps...";const {data,error}=await db.from("apps").select("*").order("created_at",{ascending:false}).limit(100);if(error){$("status").textContent="Unable to load apps: "+error.message;return}apps=data||[];$("status").textContent=apps.length?apps.length+" apps available":"No apps published yet";renderApps(apps)}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function renderApps(list){$("appGrid").innerHTML=list.map(a=>'<article class="card"><img src="'+esc(a.icon_url||"assets/icon.png")+'" onerror="this.src=\'assets/icon.png\'" alt=""><div class="card-body"><h3>'+esc(a.name||"Unnamed App")+'</h3><div class="meta">'+esc(a.developer||"PaliaAPK HUB")+" · "+esc(a.version||"Latest")+'</div><button class="download" data-id="'+esc(a.id)+'">Download APK</button></div></article>').join("");document.querySelectorAll(".download").forEach(b=>b.onclick=()=>startDownload(apps.find(x=>String(x.id)===String(b.dataset.id))))}
$("search").oninput=e=>{const q=e.target.value.toLowerCase();renderApps(apps.filter(a=>String(a.name||"").toLowerCase().includes(q)||String(a.developer||"").toLowerCase().includes(q)||String(a.category||"").toLowerCase().includes(q)))};$("refresh").onclick=loadApps;
async function startDownload(a){if(!a)return;if(!auth.currentUser){$("authModal").classList.remove("hidden");return}const url=a.apk_url||a.download_url;if(!url){alert("No APK download URL is configured for this app.");return}const filename=(a.name||"PaliaAPK-HUB-App").replace(/[^a-z0-9._-]+/gi,"_")+".apk";$("downloadName").textContent="Downloading "+(a.name||"APK");$("downloadToast").classList.remove("hidden");try{const plugin=window.Capacitor?.registerPlugin?.("PaliaDownloader");if(!plugin)throw Error("Native downloader is unavailable");await plugin.addListener("downloadProgress",p=>updateProgress(p));await plugin.download({url,filename});setTimeout(()=>$("downloadToast").classList.add("hidden"),4000)}catch(e){$("downloadToast").classList.add("hidden");alert("Download failed: "+e.message)}}
function updateProgress(p){const total=Number(p.totalBytes||0),done=Number(p.downloadedBytes||0),pct=total?Math.min(100,done/total*100):0;$("progressBar").style.width=pct+"%";$("progressText").textContent=Math.round(pct)+"%";$("speedText").textContent=total?((done/1048576).toFixed(1)+" MB / "+(total/1048576).toFixed(1)+" MB"):"Downloading..."}
loadApps();